#NOT_MOVED_TO_BETTER_POS = "NOT_MOVED_TO_BETTER_POS"
#MOVED_TO_BETTER_POS = "MOVED_TO_BETTER_POS" # i.e. moved to a coin or to a place where i can attack more targets
MOVED_TO_COIN = "MOVED_TO_COIN"
NOT_MOVED_TO_COIN = "NOT_MOVED_TO_COIN"
MOVED_TO_BETTER_BOMB_POS = "MOVED_TO_BETTER_BOMB_POS"
NOT_MOVED_TO_BETTER_BOMB_POS = "NOT_MOVED_TO_BETTER_BOMB_POS"
TARGET_ATTACKED = "TARGET_ATTACKED" # i.e. BOMB PLACEMENT AFFECT A TILE
#UNNECESSARY_BOMB = "UNNECESSARY_BOMB"
#RUN_INTO_DEATH = "RUN_INTO_DEATH"
BAD_MOVE = "BAD_MOVE"
BAD_BOMB = "BAD_BOMB" # if agent tries to plant bomb but is not able to this or
                      # or if bomb is unnecesary (i.e. dont affect a target)
                      # or if planting a bomb would lead to safe death
WAITED_FOR_DEATH = "WAITED_FOR_DEATH"
USELESS_MOVE = "USELESS_MOVE"
USEFUL_MOVE  = "USEFUL_MOVE"
OPPONENT_ATTACKED = "OPPONENT_ATTACKED"
GOOD_ATTACK = "GOOD_ATTACK"
RUN_INTO_DANGER = "RUN_INTO_DANGER"
ESCAPE_FROM_DANGER = "ESCAPE_FROM_DANGER"
KAMIKAZE_HERO = "KAMIKAZE_HERO"
KAMIKAZE_INSUBORDINATOR = "KAMIKAZE_INSUBORDINATOR"
